openapi: 3.0.1
info:
  title: Bag To the Future
  description: API Documentation
  version: 0.1.0
servers:
- url: http://localhost:8084/v1
tags: []
paths:
  /certificate/message:
    post:
      tags:
      - certificate
      summary: 인증 번호 검증 API
      description: 인증 번호 검증 API입니다.
      operationId: verify-certificate-number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] verify-certificate-number"
            examples:
              verify-certificate-number:
                value: "{\"phoneNumber\":[\"010\",\"1234\",\"5678\"],\"certificationNumber\"\
                  :\"185479\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] verify-certificate-number"
              examples:
                verify-certificate-number:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\"}"
  /certificate/message/{phoneNumber}:
    get:
      tags:
      - certificate
      summary: 인증 번호 발급 API
      description: 인증 번호 발급 API입니다.
      operationId: get-certificate-number
      parameters:
      - name: phoneNumber
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] get-certificate-number"
              examples:
                get-certificate-number:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    certification_number\":\"731014\"}}"
components:
  schemas:
    '[response] verify-certificate-number':
      title: "[response] verify-certificate-number"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    '[response] get-certificate-number':
      title: "[response] get-certificate-number"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - certification_number
          type: object
          properties:
            certification_number:
              type: string
              description: 인증 번호
        message:
          type: string
          description: 응답 메시지
    '[request] verify-certificate-number':
      title: "[request] verify-certificate-number"
      required:
      - certificationNumber
      - phoneNumber
      type: object
      properties:
        phoneNumber:
          type: array
          description: 전화번호
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
        certificationNumber:
          type: string
          description: 인증번호
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []