openapi: 3.0.1
info:
  title: Bag To the Future
  description: API Documentation
  version: 0.1.0
servers:
- url: http://localhost:8080/v1
tags: []
paths:
  /member/login:
    post:
      tags:
      - member
      summary: 일반 로그인 API
      description: 일반 로그인 API 입니다.
      operationId: login-member
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] member-login"
            examples:
              login-member:
                value: "{\"password\":\"123456\",\"email\":\"kildong.hong@naver.com\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] member-login"
              examples:
                login-member:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"accessToken\"\
                    :\"access token\",\"refreshToken\":\"resfresh token\"}}"
  /member/refresh:
    post:
      tags:
      - member
      summary: 토큰 갱신 API
      description: "refresh token을 이용하여 access,refresh token 갱신하는  API입니다."
      operationId: refresh-access-and-refresh-token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/member-refresh1564428056'
            examples:
              refresh-access-and-refresh-token:
                value: "{\"refreshToken\":\"5324fdswqe13dew\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/member-refresh223414243'
              examples:
                refresh-access-and-refresh-token:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"accessToken\"\
                    :\"access token\",\"refreshToken\":\"resfresh token\"}}"
  /member/register:
    post:
      tags:
      - member
      summary: 회원가입 API
      description: 회원가입 API 입니다.
      operationId: register-member
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] member-register"
            examples:
              register-member:
                value: "{\"password\":\"123456\",\"phoneNumber\":[\"010\",\"1234\"\
                  ,\"5678\"],\"passwordConfirm\":\"123456\",\"name\":\"홍길동\",\"email\"\
                  :\"kildong.hong@naver.com\"}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] member-register"
              examples:
                register-member:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    id\":1}}"
  /member/login/oauth:
    post:
      tags:
      - member
      summary: 소셜 로그인 API
      description: 소셜 로그인 API 입니다.
      operationId: oauth-login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthLoginDto'
            examples:
              oauth-login:
                value: "{\"authorizationCode\":\"authorizationCode\",\"providerType\"\
                  :\"KAKAO\",\"rolesType\":\"ROLE_USER\",\"state\":\"state\",\"token\"\
                  :\"accessToken\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginTokenDto'
              examples:
                oauth-login:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"accessToken\"\
                    :\"accessToken\",\"refreshToken\":\"resfreshToken\"}}"
components:
  schemas:
    member-refresh223414243:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - accessToken
          - refreshToken
          type: object
          properties:
            accessToken:
              type: string
              description: 갱신된 Access Token
            refreshToken:
              type: string
              description: 갱신된 Refresh Token
        message:
          type: string
          description: 응답 메시지
    '[request] member-register':
      title: "[request] member-register"
      required:
      - email
      - name
      - password
      - passwordConfirm
      - phoneNumber
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        phoneNumber:
          type: array
          description: 전화번호
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
        passwordConfirm:
          type: string
          description: 비밀번호 확인
        name:
          type: string
          description: 이름
        email:
          type: string
          description: 이메일
    OAuthLoginDto:
      title: OAuthLoginDto
      required:
      - authorizationCode
      - providerType
      - rolesType
      type: object
      properties:
        rolesType:
          type: string
          description: "유저의 자격 값입니다. ( 관리자 : ROLE_ADMIN, 일반 회원 : ROLE_USER, 가게 회원\
            \ : ROLE_STORE_OWNER )"
        authorizationCode:
          type: string
          description: Authorization Server에서 받은 인증 코드입니다.
        state:
          type: string
          description: 네이버 소셜 로그인 시 필요한 state 값입니다. 'state' string 주면 됩니다. ( KAKAO
            로그인 시 null )
          nullable: true
        providerType:
          type: string
          description: "어떤 소셜 로그인인지 입력 값입니다. ( 카카오 로그인 : KAKAO, 네이버 로그인 : NAVER )"
        token:
          type: string
          description: 소셜 인증 서버에서 발급받은 접근 토큰 값입니다.
          nullable: true
    '[request] member-login':
      title: "[request] member-login"
      required:
      - email
      - password
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        email:
          type: string
          description: 이메일
    '[response] member-login':
      title: "[response] member-login"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - accessToken
          - refreshToken
          type: object
          properties:
            accessToken:
              type: string
              description: Access Token
            refreshToken:
              type: string
              description: Refresh Token
        message:
          type: string
          description: 응답 메시지
    member-refresh1564428056:
      required:
      - refreshToken
      type: object
      properties:
        refreshToken:
          type: string
          description: refresh token 값입니다.
    LoginTokenDto:
      title: LoginTokenDto
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - accessToken
          - refreshToken
          type: object
          properties:
            accessToken:
              type: string
              description: Access Token
            refreshToken:
              type: string
              description: Refresh Token
        message:
          type: string
          description: 응답 메시지
    '[response] member-register':
      title: "[response] member-register"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - id
          type: object
          properties:
            id:
              type: number
              description: 사용자 ID
        message:
          type: string
          description: 응답 메시지
