version: '3'

services:
  db:
    image: mysql:8.0 # mysql 이미지
    ports:
      - "3306:3306" # TCP 포트 : 데이터베이스 연결 포트
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 3s
      retries: 5
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

  bagtothefuture-nginx:
    image: ${DOCKER_USERNAME}/bagtothefuture-nginx:latest #swagger(index.html + reverse proxy) 역할
    ports:
      - "80:80"
    restart: always
    depends_on:
      - bagtothefuture-member
      - bagtothefuture-store
      - bagtothefuture-event

  bagtothefuture-member:
    image: ${DOCKER_USERNAME}/bagtothefuture-member:latest # member api 이미지
    ports:
      - "8080:8080"
    container_name: member
    environment:
      SPRING_PROFILES_ACTIVE: dev # dev 프로파일 활성화
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test
#      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
#      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      OAUTH_KAKAO_CLIENTID: ${OAUTH_KAKAO_CLIENTID}
      OAUTH_KAKAO_REDIRECT_URL: ${OAUTH_KAKAO_REDIRECT_URL}
      OAUTH_KAKAO_CLIENT_SECRET: ${OAUTH_KAKAO_CLIENT_SECRET}
      OAUTH_NAVER_CLIENTID: ${OAUTH_NAVER_CLIENTID}
      OAUTH_NAVER_CLIENT_SECRET: ${OAUTH_NAVER_CLIENT_SECRET}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy        // rds 사용시 주석 처리 필요
      redis:
        condition: service_healthy

  bagtothefuture-store:
    image: ${DOCKER_USERNAME}/bagtothefuture-store:latest # store api 이미지
    ports:
      - "8081:8081"
    container_name: stores
    environment:
      SPRING_PROFILES_ACTIVE: dev # dev 프로파일 활성화
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test
#      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
#      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy    // rds 사용시 주석 처리 필요
      redis:
        condition: service_healthy

  bagtothefuture-event:
    image: ${DOCKER_USERNAME}/bagtothefuture-event:latest # event api 이미지
    ports:
      - "8084:8084"
    container_name: event
    environment:
      SPRING_PROFILES_ACTIVE: dev # dev 프로파일 활성화
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test
#      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
#      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy    // rds 사용시 주석 처리 필요
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]