openapi: 3.0.1
info:
  title: Bag To the Future
  description: API Documentation
  version: 0.1.0
servers:
- url: http://localhost:8084/v1
tags: []
paths:
  /certificate/email:
    get:
      tags:
      - certificate
      summary: 인증 메일 검증
      description: "인증 메일 검증 API입니다. 메일 수신자가 링크를 클릭하고, 이 API를 통해 인증하게 됩니다."
      operationId: verify-certificate-email
      responses:
        "200":
          description: "200"
          content:
            text/html;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/certificate-email486549215'
              examples:
                verify-certificate-email:
                  value: |-
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <title>인증 결과</title>
                        <meta charset="utf-8">
                    </head>
                        <h1>성공적으로 인증되었습니다. 앱 화면으로 돌아가 주세요.</h1>
                    </html>
    post:
      tags:
      - certificate
      summary: 인증 메일 전송 API
      description: 인증 메일 전송 API 입니다.
      operationId: send-certificate-email
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/certificate-email486549215'
            examples:
              send-certificate-email:
                value: "{\"email\":\"test@example.com\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] send-certificate-email"
              examples:
                send-certificate-email:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"mail_expiration_seconds\"\
                    :600}}"
  /certificate/message:
    post:
      tags:
      - certificate
      summary: 인증 번호 검증 API
      description: 인증 번호 검증 API입니다.
      operationId: verify-certificate-number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/[request] verify-certificate-number"
            examples:
              verify-certificate-number:
                value: "{\"phoneNumber\":[\"010\",\"1234\",\"5678\"],\"certificationNumber\"\
                  :\"418790\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] verify-certificate-number"
              examples:
                verify-certificate-number:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\"}"
  /certificate/message/{phoneNumber}:
    post:
      tags:
      - certificate
      summary: 인증 번호 발급 API
      description: 인증 번호 발급 API입니다.
      operationId: get-certificate-number
      parameters:
      - name: phoneNumber
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] get-certificate-number"
              examples:
                get-certificate-number:
                  value: "{\"code\":201,\"message\":\"정상적으로 생성되었습니다.\",\"data\":{\"\
                    certification_number\":\"374645\"}}"
  /certificate/email/{email}/status:
    get:
      tags:
      - certificate
      summary: 이메일 인증 상태 확인
      description: 이메일 인증 상태 확인 API입니다.
      operationId: check-certificate-email-status
      parameters:
      - name: email
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/[response] check-certificate-email-status"
              examples:
                check-certificate-email-status:
                  value: "{\"code\":200,\"message\":\"정상 처리되었습니다.\",\"data\":{\"is_certificated\"\
                    :true}}"
components:
  schemas:
    '[response] send-certificate-email':
      title: "[response] send-certificate-email"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - mail_expiration_seconds
          type: object
          properties:
            mail_expiration_seconds:
              type: number
              description: 인증 만료 시간(초)
        message:
          type: string
          description: 응답 메시지
    '[response] check-certificate-email-status':
      title: "[response] check-certificate-email-status"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - is_certificated
          type: object
          properties:
            is_certificated:
              type: boolean
              description: "인증 여부. true: 인증 / false: 미인증"
        message:
          type: string
          description: 응답 메시지
    '[response] get-certificate-number':
      title: "[response] get-certificate-number"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        data:
          required:
          - certification_number
          type: object
          properties:
            certification_number:
              type: string
              description: 인증 번호
        message:
          type: string
          description: 응답 메시지
    '[response] verify-certificate-number':
      title: "[response] verify-certificate-number"
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    certificate-email486549215:
      type: object
    '[request] verify-certificate-number':
      title: "[request] verify-certificate-number"
      required:
      - certificationNumber
      - phoneNumber
      type: object
      properties:
        phoneNumber:
          type: array
          description: 전화번호
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
        certificationNumber:
          type: string
          description: 인증번호
