jwt:
  refresh-expiration-seconds: 36000 # 리프래쉬 토큰 만료시간: 10시간

certification:
  mail:
    expiration-seconds: 600 # 이메일 인증 만료 시간
  message:
    expiration-seconds: 180 # 인증 만료시간

s3:
  bucket: # s3 버킷명
    image: bagtothefuture-static-image