spring:
  profiles:
    include: domain, infra, security
    active: dev
  jpa:
    open-in-view: false # view, Controller 단에서 Lazy를 사용하지 않음
    properties:
      hibernate:
        show_sql: true # sql query console 창에 표시 여부
        format_sql: true # console 창에 보여줄때 format 여부

  certification:
    #    coolsms:
    #      fromPhoneNumber: ${COOL_SMS_FROM_PHONE_NUMBER}
    #      api: ${COOL_SMS_API_KEY}
    #      secret: ${COOL_SMS_API_SECRET_KEY}
    mail:
      baseurl: "http://localhost:8084/v1"
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000 # SMTP 서버 연결 시도 timeout
        smtp.starttls.enable: true
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

# default swagger ui url : http://server:port/context-path/swagger-ui.html
springdoc:
  api-docs:
    enabled: true

server:
  port: 8084
  servlet:
    context-path: /v1
