spring:
  profiles:
    include: domain, infra, security
    active: dev
  jpa:
    open-in-view: false # view, Controller 단에서 Lazy를 사용하지 않음
    properties:
      hibernate:
        show_sql: true # sql query console 창에 표시 여부
        format_sql: true # console 창에 보여줄때 format 여부

  certification:
    coolsms:
      fromPhoneNumber: 01000000000
      api: test
      secret: test

server:
  port: 8084
  servlet:
    context-path: /v1